# Generated by Django 2.2.7 on 2020-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('manager', 'manager'), ('lecture', 'lecture')], max_length=50)),
                ('department', models.CharField(choices=[('SOFTWARE_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'), ('COMPUTERSYSTEMSENGINEERING', 'COMPUTERSYSTEMSENGINEERING'), ('INFORMATICS', 'INFORMATICS'), ('COMMUNICATION_NETWORKS', 'COMMUNICATION_NETWORKS')], max_length=50)),
                ('faculty', models.CharField(choices=[('INFORMATION_AND_COMMUNICATION_TECHNOLOGY', 'INFORMATION_AND_COMMUNICATION_TECHNOLOGY'), ('ENGINEERING_AND_ENVIRONMENT', 'ENGINEERING_AND_ENVIRONMENT')], max_length=50)),
            ],
        ),
    ]
