# Generated by Django 2.2.7 on 2020-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200718_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.CharField(choices=[('SOFTWARE_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'), ('COMPUTERSYSTEMSENGINEERING', 'COMPUTERSYSTEMSENGINEERING'), ('INFORMATICS', 'INFORMATICS'), ('COMMUNICATION_NETWORKS', 'COMMUNICATION_NETWORKS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='faculty',
            field=models.CharField(choices=[('INFORMATION_AND_COMMUNICATION_TECHNOLOGY', 'INFORMATION_AND_COMMUNICATION_TECHNOLOGY'), ('ENGINEERING_AND_ENVIRONMENT', 'ENGINEERING_AND_ENVIRONMENT')], max_length=50),
        ),
    ]
